Fix max reserved students
perlus3/HeadHunterBE pull request #28
Opened 2023-05-11 22:24 UTC by perlus3

zmiana dodawania studentów, aby ignorowało powtarzające się adresy email, a pozostałe dodawało, działa ale obsługa błędów jest beznadziejna i jak doda użytkownika to zwraca błąd, w sensie nie mogłem zwrócić w inny sposób komunikatu o tym kto został dodany ( chyba że to zbędne, to wywale )

2023-05-12 12:11 UTC, MalgorzataJu approved these changes

2023-05-12 14:05 UTC, baradoslaw requested changes

2023-05-12 14:05 UTC, baradoslaw commented on src/register/register.service.ts
> +          `Nie dodano żadnego nowego użytkownika, ponieważ ${emails} już istanieją w bazie danych`,
Nie zadziała tutaj return ?

2023-05-12 14:05 UTC, baradoslaw commented on src/register/register.service.ts
> +        throw new BadRequestException(`Dodano użytkowników ${newEmails}`);
Jak wyżej

2023-05-13 16:23 UTC, Cynio007 approved these changes

2023-05-16 19:25 UTC, merged